### ISSUE TITLE
The plugin crisp could not be built due to the issue

### ISSUE THREAD

**Issue by jpmehedi** [lunahq/flutter-crisp#6]
When i was build my application then i am faceing this issue. i was run: flutter build apk

![Screenshot (54)](https://user-images.githubusercontent.com/29401466/99945349-ae764000-2d9e-11eb-91f6-ba39a716cda3.png)

**Comment by f2acode** [comment]
Hey, this is strange since the file mentioned has the import reference:

`import androidx.annotation.NonNull;`

Are you using code shrinking? This could be the reason, then you could `flutter build apk --no-shrink` or add the keep instruction to your `proguard-rules.pro` file:

`-keep class io.flutter.app.** { *; }`
